#!/usr/bin/env node
const fs = require("fs");
const abi = require("ethjs-abi");

const abi_path = process.argv[2];

const json = JSON.parse(fs.readFileSync(abi_path))

const get_fabi_name = fabi =>
  "  function " + fabi.name + "(" + fabi.inputs.map(i => i.type + " " + i.name).join(", ") + ") external" + ((fabi.outputs || []).length > 0 ? (" returns (" + fabi.outputs.map(o => o.type + (o.name && (" " + o.name) || "") ).join(", ") + ")"): "") + ";"


const interface_str = json
  .map(get_fabi_name)


const scafholding = json
  .filter(fabi => fabi.type == "function")
  .map(fabi => {
    let sig = abi.encodeSignature(fabi);
    let name = get_fabi_name(fabi)

    return {
      sig,
      name
    }
  })
  .sort((a, b) => parseInt(a.sig.slice(2), 16) - parseInt(b.sig.slice(2), 16))
  // .map(e => e.sig)

console.log(interface_str.join("\n"));

